<?php

/**
 * Implements hook_theme().
 */
function quiz_theme($existing, $type, $theme, $path): array {
  return [
    'quiz' => [
      'variables' => [
        'nodes' => NULL,
        'cache' => [
          'max-age' => 1,
        ],
      ],
    ],
    'b1_practice_test' => [
      'variables' => [
        'terms' => NULL,
        'cache' => [
          'max-age' => 0,
        ],
      ],
    ],
    'b1_practice_test_result' => [
      'variables' => [
        'node' => NULL,
        'quiz' => NULL,
        'collection' => NULL,
        'results' => NULL,
        'sections' => NULL,
        'score' => NULL,
        'cache' => [
          'max-age' => 0,
        ],
      ],
    ],
    'question_number' => [
      'variables' => [
        'questions' => NULL,
        'cache' => [
          'max-age' => 0,
        ],
      ],
    ],
  ];
}

